# Un-comment the version field if you get an 'unsupported Compose file version: 1.0' ERROR

#version: '3.8'
networks:
  counter-net:
    driver: overlay
    driver_opts:
      encrypted: 'yes'

services:
  web-fe:
    image: nigelpoulton/ddd-book:swarm-appv2
    command: python app.py
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - counter-net
    ports:
      - published: 5001
        target: 8080
  redis:
    image: "redis:alpine"
    networks:
      counter-net:
